const KEY='tcg-scout-v1-data';
const SESSION='tcg-scout-v1-session';
const now=()=>new Date();
const iso=(d=new Date())=>d.toISOString();
const uid=()=>crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
const fmtTime=s=>new Date(s).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
const fmtDate=s=>new Date(s).toLocaleDateString([], {month:'short',day:'numeric'});
const dayKey=d=>new Date(d).toLocaleDateString('en-US',{weekday:'short'});
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));
const periodFor = d => { const h=new Date(d).getHours(); if(h<11)return 'Morning'; if(h<13)return 'Noon'; if(h<17)return 'Afternoon'; return 'Evening'; };
const signalIcon={stocked:'🟢',possible:'🟡',empty:'🔴',line:'👥',evidence:'🟠'};
const signalName={stocked:'Stock seen',possible:'Possible restock',empty:'Empty / sold out',line:'People lining up',evidence:'Evidence of restock'};

function seed(){
 const stores=[
  {id:'s1',name:'Target — Riverside',chain:'Target',area:'Local',active:true},
  {id:'s2',name:'Walmart — North',chain:'Walmart',area:'Local',active:true},
  {id:'s3',name:'Card Corner',chain:'Local shop',area:'Downtown',active:true}
 ];
 const products=[
  {id:'p1',name:'One Piece Booster Box',tcg:'One Piece',active:true},
  {id:'p2',name:'One Piece Double Pack',tcg:'One Piece',active:true},
  {id:'p3',name:'Pokémon ETB',tcg:'Pokémon',active:true}
 ];
 const d=new Date(); const mk=(days,h,m=0)=>{const x=new Date(d);x.setDate(x.getDate()-days);x.setHours(h,m,0,0);return x.toISOString()};
 const reports=[
  {id:uid(),storeId:'s1',type:'line',occurredAt:mk(0,9,20),createdAt:mk(0,9,24),period:'Morning',source:'Firsthand',notes:'Small line near cards.',productId:'p1',price:null,condition:null,memberId:'m2'},
  {id:uid(),storeId:'s1',type:'stocked',occurredAt:mk(0,9,45),createdAt:mk(0,9,48),period:'Morning',source:'Friend',notes:'OP booster boxes on shelf.',productId:'p1',price:119.99,condition:'Sealed',memberId:'m2'},
  {id:uid(),storeId:'s1',type:'empty',occurredAt:mk(0,12,15),createdAt:mk(0,12,16),period:'Noon',source:'Firsthand',notes:'Booster boxes gone.',productId:'p1',price:null,condition:null,memberId:'m3'},
  {id:uid(),storeId:'s2',type:'possible',occurredAt:mk(1,14,10),createdAt:mk(1,14,20),period:'Afternoon',source:'Phone call',notes:'Employee said cards came earlier.',productId:'p2',price:null,condition:null,memberId:'m3'},
  {id:uid(),storeId:'s3',type:'stocked',occurredAt:mk(2,11,45),createdAt:mk(2,12,0),period:'Noon',source:'Social media',notes:'Shop posted restock photo.',productId:'p1',price:134.99,condition:'Sealed',memberId:'m2'},
  {id:uid(),storeId:'s3',type:'stocked',occurredAt:mk(5,15,30),createdAt:mk(5,15,35),period:'Afternoon',source:'Firsthand',notes:'Open box discount.',productId:'p1',price:108,condition:'Unsealed',memberId:'m4'},
  {id:uid(),storeId:'s1',type:'evidence',occurredAt:mk(7,10,10),createdAt:mk(7,13,0),period:'Morning',source:'Friend',notes:'Fresh display, employee said vendor already came.',productId:'p1',price:null,condition:null,memberId:'m3'},
  {id:uid(),storeId:'s1',type:'stocked',occurredAt:mk(14,9,35),createdAt:mk(14,9,40),period:'Morning',source:'Firsthand',notes:'OP shelf restocked.',productId:'p1',price:119.99,condition:'Sealed',memberId:'m2'},
 ];
 return {stores,products,reports,members:[
  {id:'m1',name:'You',email:'admin@example.com',role:'admin',lastActive:iso(),logins:18,sessions:42,reports:6,activeDays:7},
  {id:'m2',name:'Alex',email:'alex@example.com',role:'member',lastActive:mk(0,10),logins:4,sessions:19,reports:10,activeDays:6},
  {id:'m3',name:'Jordan',email:'jordan@example.com',role:'member',lastActive:mk(0,8),logins:3,sessions:11,reports:7,activeDays:4},
  {id:'m4',name:'Sam',email:'sam@example.com',role:'member',lastActive:mk(3,17),logins:2,sessions:5,reports:3,activeDays:2}
 ], savedFilters:[{id:'f1',name:'OP Only',tcg:'One Piece',range:30,ownerId:'m1'}], settings:{periods:['Morning','Noon','Afternoon','Evening']}};
}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch{return seed()}}
let data=load(); let state={view:'home',trendTab:'activity',filters:{tcg:'All',storeId:'All',period:'All',range:30,condition:'All',type:'All'},sheet:null,toast:null};
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION))}catch{return null}}
function setSession(s){localStorage.setItem(SESSION,JSON.stringify(s))}
function activeStores(){return data.stores.filter(x=>x.active)} function activeProducts(){return data.products.filter(x=>x.active)}
function currentMember(){let s=getSession();return data.members.find(m=>m.id===s?.memberId)||null}
function toast(msg){state.toast=msg;render();setTimeout(()=>{state.toast=null;render()},1800)}
function last7(){return Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-(6-i));d.setHours(0,0,0,0);return d})}
function reportsForStore(storeId){return data.reports.filter(r=>r.storeId===storeId).sort((a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt))}
function daySignals(storeId,d){return data.reports.filter(r=>r.storeId===storeId && new Date(r.occurredAt).toDateString()===d.toDateString()).map(r=>signalIcon[r.type]).filter((v,i,a)=>a.indexOf(v)===i).slice(0,2).join('')||'·'}
function latestStatus(storeId){const r=reportsForStore(storeId)[0]; if(!r)return {text:'No activity',cls:''};return {text:`${signalIcon[r.type]} ${signalName[r.type]}`,cls:r.type==='stocked'?'green':r.type==='empty'?'red':'yellow',r}}

function loginView(){return `<div class="login"><div class="login-card"><div class="logo">TCG</div><h1>TCG Scout</h1><p>Fast local restock, price and trend intelligence for your group.</p><div class="field"><label>Email</label><input id="email" type="email" placeholder="you@example.com" autocomplete="email" /></div><button class="btn wide" data-action="magic-login">Send magic link</button><div class="demo-note">Prototype mode: the button signs you in as Admin so you can test the full mobile experience. Supabase magic-link wiring is included in the backend plan.</div></div></div>`}
function topbar(){const m=currentMember();return `<header class="topbar"><div class="brandrow"><div class="brand"><div class="logo">TCG</div><div><div class="title">TCG Scout</div><div class="subtitle">${escapeHtml(m?.name)} · ${m?.role==='admin'?'Admin':'Member'}</div></div></div><button class="pill" data-action="share-app">Share</button></div></header>`}
function home(){return `<section class="section"><div class="section-head"><h2>7-day activity</h2><button class="pill" data-action="open-stores">Manage stores</button></div>${activeStores().map(store=>{let st=latestStatus(store.id),last=st.r;return `<div class="card" data-store="${store.id}"><div class="store-head"><div><div class="store-name">${escapeHtml(store.name)}</div><div class="store-meta">${escapeHtml(store.chain)} · ${escapeHtml(store.area)}</div></div><div class="status ${st.cls}">${escapeHtml(st.text)}</div></div><div class="week">${last7().map(d=>`<div class="day"><strong>${dayKey(d)}</strong><div class="signals">${daySignals(store.id,d)}</div></div>`).join('')}</div><div class="latest"><span>${last?`${last.period} · ${fmtTime(last.occurredAt)}`:'No recent report'}</span><button class="chip" data-action="text-store" data-id="${store.id}">Text ↗</button></div></div>`}).join('')}</section><section class="section"><div class="section-head"><h2>Quick report</h2><span class="muted">2 taps is enough</span></div><div class="quick-grid">${Object.entries({stocked:'Stocked',empty:'Empty',possible:'Possible',line:'Line'}).map(([k,v])=>`<button class="big-action" data-action="quick-report" data-type="${k}"><span>${signalIcon[k]}</span><b>${v}</b><small>Details optional</small></button>`).join('')}</div></section>`}
function applyFilters(){const f=state.filters;let cutoff=new Date();cutoff.setDate(cutoff.getDate()-Number(f.range||30));return data.reports.filter(r=>{let p=data.products.find(x=>x.id===r.productId);return new Date(r.occurredAt)>=cutoff&&(f.tcg==='All'||p?.tcg===f.tcg)&&(f.storeId==='All'||r.storeId===f.storeId)&&(f.period==='All'||r.period===f.period)&&(f.condition==='All'||r.condition===f.condition)&&(f.type==='All'||r.type===f.type)})}
function trendActivity(reps){let groups={};reps.forEach(r=>{let k=`${r.storeId}|${dayKey(r.occurredAt)}|${r.period}`;groups[k]=(groups[k]||0)+1});return Object.entries(groups).map(([k,count])=>{let [storeId,day,period]=k;return {store:data.stores.find(s=>s.id===storeId)?.name||'Store',day,period,count}}).sort((a,b)=>b.count-a.count).slice(0,12)}
function trending(){const reps=applyFilters(); const activity=trendActivity(reps);const stock=reps.filter(r=>r.type==='stocked').length,line=reps.filter(r=>r.type==='line').length,empty=reps.filter(r=>r.type==='empty').length;return `<section class="section"><div class="section-head"><h2>Trending</h2><button class="pill" data-action="open-filters">Filter ⚙</button></div><div class="chips">${[{name:'All',id:null},...data.savedFilters.filter(f=>f.ownerId===currentMember().id)].map(f=>`<button class="chip ${f.id&&state.activeSaved===f.id?'active':''}" data-action="saved-filter" data-id="${f.id||''}">${escapeHtml(f.name)}</button>`).join('')}<button class="chip" data-action="save-filter">＋ Save</button></div><div class="tabs" style="margin-top:12px">${['activity','products','prices'].map(t=>`<button class="chip ${state.trendTab===t?'active':''}" data-action="trend-tab" data-tab="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>${state.trendTab==='activity'?`<div class="card"><div class="row between"><div><h3>Best observed windows</h3><div class="tiny">Based on ${reps.length} matching reports</div></div><span class="heat">🔥</span></div><div class="metric-grid"><div class="metric"><b>${stock}</b><span>Stock signals</span></div><div class="metric"><b>${line}</b><span>Line reports</span></div><div class="metric"><b>${empty}</b><span>Sold out</span></div></div>${activity.length?activity.map((x,i)=>`<div class="trend-row"><div><div class="trend-main">${escapeHtml(x.store)}</div><div class="trend-sub">${x.day} · ${x.period} · ${x.count} observation${x.count===1?'':'s'}</div></div><div class="heat">${'🔥'.repeat(Math.min(3,Math.ceil(x.count/2)))}</div></div>`).join(''):'<div class="empty">No reports match these filters.</div>'}</div>`:state.trendTab==='products'?productTrend(reps):priceTrend(reps)}</section>`}
function productTrend(reps){let c={};reps.forEach(r=>{if(r.productId)c[r.productId]=(c[r.productId]||0)+1});let rows=Object.entries(c).sort((a,b)=>b[1]-a[1]);return `<div class="card"><h3>Products showing up</h3>${rows.length?rows.map(([id,n])=>`<div class="trend-row"><div><div class="trend-main">${escapeHtml(data.products.find(p=>p.id===id)?.name||'Product')}</div><div class="trend-sub">${escapeHtml(data.products.find(p=>p.id===id)?.tcg||'')}</div></div><b>${n}</b></div>`).join(''):'<div class="empty">No product activity yet.</div>'}</div>`}
function priceTrend(reps){let rows=reps.filter(r=>r.price!=null).sort((a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt));return `<div class="card"><h3>Observed prices</h3>${rows.length?rows.map(r=>`<div class="price-row"><div><b>${escapeHtml(data.products.find(p=>p.id===r.productId)?.name||'Product')}</b><div class="tiny">${escapeHtml(data.stores.find(s=>s.id===r.storeId)?.name||'Store')} · ${fmtDate(r.occurredAt)}</div></div><span class="badge">${escapeHtml(r.condition||'—')}</span><b>$${Number(r.price).toFixed(2)}</b></div>`).join(''):'<div class="empty">No matching price reports.</div>'}</div>`}
function report(){return `<section class="section"><div class="section-head"><h2>Report</h2><span class="muted">Only status is required</span></div><div class="quick-grid">${['stocked','empty','possible','line','evidence'].map(k=>`<button class="big-action" data-action="report-type" data-type="${k}"><span>${signalIcon[k]}</span><b>${signalName[k]}</b><small>${k==='line'?'Optional line size':'Add details if useful'}</small></button>`).join('')}</div></section><section class="section"><div class="card"><div class="row between"><div><h3>Products & stores</h3><div class="tiny">Members can add/archive both</div></div><button class="btn secondary" data-action="open-catalog">Manage</button></div></div></section>`}
function admin(){const m=currentMember();if(m?.role!=='admin')return `<div class="empty">Admin only.</div>`;let members=[...data.members].sort((a,b)=>b.sessions-a.sessions);return `<section class="section"><div class="section-head"><h2>Admin</h2><span class="muted">Only you can see this</span></div><div class="card"><h3>Member activity</h3><div class="tiny">Sessions are more useful than magic-link login count because members stay signed in.</div>${members.map(x=>`<div class="member-row"><div><b>${escapeHtml(x.name)}</b><div class="tiny">${escapeHtml(x.email)} · ${x.role}</div></div><div><b>${x.sessions}</b><div class="tiny">sessions</div></div><div><b>${x.activeDays}/7</b><div class="tiny">active days</div></div></div>`).join('')}</div><div class="card"><div class="row between"><div><h3>Member management</h3><div class="tiny">Invite/remove access and backend controls live here.</div></div><button class="btn secondary" data-action="members">Manage</button></div></div><div class="card"><div class="row between"><div><h3>Prototype data</h3><div class="tiny">Reset local demo data if needed.</div></div><button class="btn danger" data-action="reset">Reset</button></div></div></section>`}
function nav(){return `<nav class="bottom-nav">${[{v:'home',i:'⌂',n:'Home'},{v:'trending',i:'↗',n:'Trending'},{v:'report',i:'＋',n:'Report'},{v:'admin',i:'⚙',n:'Admin'}].map(x=>`<button class="nav-btn ${state.view===x.v?'active':''}" data-action="nav" data-view="${x.v}"><span>${x.i}</span>${x.n}</button>`).join('')}</nav>`}
function shell(){let body=state.view==='home'?home():state.view==='trending'?trending():state.view==='report'?report():admin();return `<div class="shell">${topbar()}${body}</div>${nav()}${state.sheet?sheet(state.sheet):''}${state.toast?`<div class="toast">${escapeHtml(state.toast)}</div>`:''}`}
function sheet(type){if(type==='filters')return filterSheet();if(type==='report')return reportSheet(state.reportType);if(type==='catalog')return catalogSheet();if(type==='stores')return storesSheet();if(type==='members')return membersSheet();return ''}
function filterSheet(){const f=state.filters;return `<div class="sheet"><div class="sheet-card"><div class="sheet-title"><h2>Trend filters</h2><button class="close" data-action="close-sheet">×</button></div><div class="field"><label>TCG</label><select id="f-tcg"><option>All</option>${[...new Set(activeProducts().map(p=>p.tcg))].map(x=>`<option ${f.tcg===x?'selected':''}>${escapeHtml(x)}</option>`).join('')}</select></div><div class="field"><label>Store</label><select id="f-store"><option value="All">All stores</option>${activeStores().map(s=>`<option value="${s.id}" ${f.storeId===s.id?'selected':''}>${escapeHtml(s.name)}</option>`).join('')}</select></div><div class="field"><label>Time of day</label><select id="f-period">${['All',...data.settings.periods].map(x=>`<option ${f.period===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Report type</label><select id="f-type"><option value="All">All</option>${Object.entries(signalName).map(([k,v])=>`<option value="${k}" ${f.type===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Condition</label><select id="f-condition">${['All','Sealed','Unsealed','Damaged'].map(x=>`<option ${f.condition===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Date range</label><select id="f-range">${[7,30,90,365].map(x=>`<option value="${x}" ${Number(f.range)===x?'selected':''}>Last ${x} days</option>`).join('')}</select></div><button class="btn wide" data-action="apply-filters">Apply filters</button></div></div>`}
function reportSheet(type){return `<div class="sheet"><div class="sheet-card"><div class="sheet-title"><div><h2>${signalIcon[type]} ${signalName[type]}</h2><div class="tiny">Submit now or add optional details.</div></div><button class="close" data-action="close-sheet">×</button></div><div class="field"><label>Store</label><select id="r-store">${activeStores().map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('')}</select></div><div class="field"><label>Time bucket</label><select id="r-period">${data.settings.periods.map(x=>`<option ${periodFor(new Date())===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Product <span class="optional">optional</span></label><select id="r-product"><option value="">None</option>${activeProducts().map(p=>`<option value="${p.id}">${escapeHtml(p.tcg)} — ${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="field"><label>Source <span class="optional">optional</span></label><select id="r-source">${['Firsthand','Friend','Phone call','Social media','Store employee','Other'].map(x=>`<option>${x}</option>`).join('')}</select></div>${type==='line'?`<div class="field"><label>Line size <span class="optional">optional</span></label><select id="r-line"><option value="">Not specified</option><option>Small</option><option>Medium</option><option>Large</option></select></div>`:''}<div class="row"><div class="field" style="flex:1"><label>Price <span class="optional">optional</span></label><input id="r-price" inputmode="decimal" placeholder="$" /></div><div class="field" style="flex:1"><label>Condition <span class="optional">optional</span></label><select id="r-condition"><option value="">—</option><option>Sealed</option><option>Unsealed</option><option>Damaged</option></select></div></div><div class="field"><label>Notes / secondary evidence <span class="optional">optional</span></label><textarea id="r-notes" placeholder="Friend said..., shop posted..., employee said..."></textarea></div><button class="btn wide" data-action="submit-report" data-type="${type}">Submit report</button></div></div>`}
function catalogSheet(){return `<div class="sheet"><div class="sheet-card"><div class="sheet-title"><h2>Products & stores</h2><button class="close" data-action="close-sheet">×</button></div><h3>Products</h3>${data.products.map(p=>`<div class="trend-row"><div><b>${escapeHtml(p.name)}</b><div class="tiny">${escapeHtml(p.tcg)} · ${p.active?'Active':'Archived'}</div></div><button class="chip" data-action="toggle-product" data-id="${p.id}">${p.active?'Archive':'Restore'}</button></div>`).join('')}<div class="field"><label>Add product</label><input id="new-product" placeholder="Product name" /><div class="spacer"></div><select id="new-tcg"><option>One Piece</option><option>Pokémon</option><option>MTG</option><option>Lorcana</option><option>Sports</option></select></div><button class="btn wide" data-action="add-product">Add product</button><div class="spacer"></div><h3 style="margin-top:22px">Stores</h3>${data.stores.map(s=>`<div class="trend-row"><div><b>${escapeHtml(s.name)}</b><div class="tiny">${escapeHtml(s.chain)} · ${s.active?'Active':'Archived'}</div></div><button class="chip" data-action="toggle-store" data-id="${s.id}">${s.active?'Archive':'Restore'}</button></div>`).join('')}<div class="field"><label>Add store</label><input id="new-store" placeholder="Store name" /></div><button class="btn wide" data-action="add-store">Add store</button></div></div>`}
function storesSheet(){return catalogSheet()}
function membersSheet(){return `<div class="sheet"><div class="sheet-card"><div class="sheet-title"><h2>Members</h2><button class="close" data-action="close-sheet">×</button></div>${data.members.map(m=>`<div class="trend-row"><div><b>${escapeHtml(m.name)}</b><div class="tiny">${escapeHtml(m.email)} · ${m.role}</div></div>${m.role==='admin'?'<span class="badge">Owner</span>':`<button class="chip" data-action="remove-member" data-id="${m.id}">Remove</button>`}</div>`).join('')}<div class="field"><label>Invite by email</label><input id="invite-email" type="email" placeholder="friend@example.com" /></div><button class="btn wide" data-action="invite-member">Create invite</button></div></div>`}
function render(){document.getElementById('app').innerHTML=currentMember()?shell():loginView(); if(currentMember()){const m=location.hash.match(/store=([^&]+)/); if(m){setTimeout(()=>{const el=document.querySelector(`[data-store=\"${CSS.escape(decodeURIComponent(m[1]))}\"]`); if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.style.outline='2px solid #8ce99a';setTimeout(()=>el.style.outline='',2200)}},80)}}}

async function shareText(storeId){let s=data.stores.find(x=>x.id===storeId),st=latestStatus(storeId),r=st.r;let msg=`TCG Scout — ${s.name}: ${r?`${signalIcon[r.type]} ${signalName[r.type]} · ${r.period} · ${fmtTime(r.occurredAt)}`:'No recent activity'}. View: ${location.href.split('#')[0]}#store=${storeId}`;if(navigator.share){try{await navigator.share({title:'TCG Scout update',text:msg,url:location.href.split('#')[0]+'#store='+storeId});return}catch{}}location.href='sms:?&body='+encodeURIComponent(msg)}

document.addEventListener('click',e=>{let el=e.target.closest('[data-action]');if(!el)return;let a=el.dataset.action;
 if(a==='magic-login'){let email=document.getElementById('email')?.value.trim()||'admin@example.com'; data.members[0].email=email; data.members[0].logins++;data.members[0].sessions++;data.members[0].lastActive=iso();save();setSession({memberId:'m1',at:iso()});render();toast('Signed in');}
 if(a==='nav'){state.view=el.dataset.view;render()}
 if(a==='quick-report'||a==='report-type'){state.reportType=el.dataset.type;state.sheet='report';render()}
 if(a==='close-sheet'){state.sheet=null;render()}
 if(a==='open-filters'){state.sheet='filters';render()}
 if(a==='open-catalog'||a==='open-stores'){state.sheet='catalog';render()}
 if(a==='members'){state.sheet='members';render()}
 if(a==='trend-tab'){state.trendTab=el.dataset.tab;render()}
 if(a==='apply-filters'){state.filters={tcg:document.getElementById('f-tcg').value,storeId:document.getElementById('f-store').value,period:document.getElementById('f-period').value,type:document.getElementById('f-type').value,condition:document.getElementById('f-condition').value,range:Number(document.getElementById('f-range').value)};state.activeSaved=null;state.sheet=null;render()}
 if(a==='save-filter'){let name=prompt('Name this filter (example: OP Morning Hunt)');if(name){data.savedFilters.push({id:uid(),name,...state.filters,ownerId:currentMember().id});save();toast('Filter saved')}}
 if(a==='saved-filter'){let id=el.dataset.id;if(!id){state.filters={tcg:'All',storeId:'All',period:'All',range:30,condition:'All',type:'All'};state.activeSaved=null}else{let f=data.savedFilters.find(x=>x.id===id);if(f){state.filters={tcg:f.tcg||'All',storeId:f.storeId||'All',period:f.period||'All',range:f.range||30,condition:f.condition||'All',type:f.type||'All'};state.activeSaved=id}}render()}
 if(a==='submit-report'){let price=parseFloat(document.getElementById('r-price').value);let r={id:uid(),storeId:document.getElementById('r-store').value,type:el.dataset.type,occurredAt:iso(),createdAt:iso(),period:document.getElementById('r-period').value,source:document.getElementById('r-source').value,notes:document.getElementById('r-notes').value+(document.getElementById('r-line')?.value?` Line: ${document.getElementById('r-line').value}.`:''),productId:document.getElementById('r-product').value||null,price:Number.isFinite(price)?price:null,condition:document.getElementById('r-condition').value||null,memberId:currentMember().id};data.reports.push(r);currentMember().reports++;save();state.sheet=null;state.view='home';render();toast('Report added')}
 if(a==='toggle-product'){let p=data.products.find(x=>x.id===el.dataset.id);p.active=!p.active;save();render()}
 if(a==='toggle-store'){let s=data.stores.find(x=>x.id===el.dataset.id);s.active=!s.active;save();render()}
 if(a==='add-product'){let n=document.getElementById('new-product').value.trim(),tcg=document.getElementById('new-tcg').value;if(n){data.products.push({id:uid(),name:n,tcg,active:true});save();render();toast('Product added')}}
 if(a==='add-store'){let n=document.getElementById('new-store').value.trim();if(n){data.stores.push({id:uid(),name:n,chain:'Member added',area:'Local',active:true});save();render();toast('Store added')}}
 if(a==='remove-member'){if(confirm('Remove this member access?')){data.members=data.members.filter(m=>m.id!==el.dataset.id);save();render()}}
 if(a==='invite-member'){let em=document.getElementById('invite-email').value.trim();if(em){navigator.clipboard?.writeText(`Invite ${em} to TCG Scout: ${location.href}`);toast('Invite text copied')}}
 if(a==='reset'){if(confirm('Reset prototype data?')){localStorage.removeItem(KEY);data=seed();save();render();toast('Demo reset')}}
 if(a==='text-store'){shareText(el.dataset.id)}
 if(a==='share-app'){if(navigator.share)navigator.share({title:'TCG Scout',text:'Join my local TCG Scout group',url:location.href});else navigator.clipboard?.writeText(location.href).then(()=>toast('App link copied'))}
});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
